### ISSUE TITLE
Application crashes on launch (windows 8.1) System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by nima2007** [lucasassislar/nucleuscoop#13]
Using JIT debugger I found this unhandled excaption:

An unhandled exception of type 'System.IO.DirectoryNotFoundException' occurred in mscorlib.dll

Additional information: Could not find a part of the path 'C:\Users\Nick\AppData\Roaming\Nucleus Coop\app.log'.

**Comment by lucasassislar** [comment]
Fixed on latest commit
