### ISSUE TITLE
Halo MCC Reach Support?

### ISSUE THREAD

**Issue by Rjected** [lucasassislar/nucleuscoop#136]
I'm wondering if there's any simple way for me to get this to work with Halo Reach with the MCC Collection

**Comment by Nun-z** [comment]
I second this.  Also, however, is there a not-so-easy way to get this working with Halo: Reach?

**Comment by LowProKill** [comment]
Third

**Comment by MegaMech** [comment]
It's possible, but this person doesn't seem to be sharing their secrets.
https://www.youtube.com/watch?v=KU0csl-jTpY&feature=youtu.be

**Comment by LowProKill** [comment]
Works great in MCC as of 19 May 2020

**Comment by trymeouteh** [comment]
> Works great in MCC as of 19 May 2020

Can you play campaign, custom games, firefight and forge in all the Halo titles?

**Comment by LowProKill** [comment]
Yes. All work. Have not tried forge.

**Comment by Rjected** [comment]
works on my machine
