### ISSUE TITLE
Don't starve isn't working on my computer

### ISSUE THREAD

**Issue by willingeska** [lucasassislar/nucleuscoop#158]
I used to play don't starve together on windows. I recently changed to Linux Ubuntu 20.04.2 LTS when I try and play Don't starve the game won't open. I have tried uninstalling the game and reinstalling it multiple times. I have also tried multiple proton addons through steam also. I also have the DLCs Don't Starve Hamlet and Don't Starve shipwrecked and would like to play them. my steam username is willingeska. Is there anything you can do to help me?

**Comment by willingeska** [comment]
I know you're probably busy, but can you please get back to me? I spent about 25 dollars on the games and that's a lot of money for a kid my age. Is there any way for me to fix this problem?

**Comment by Snailedlt** [comment]
Nucleus Coop doesn't support Linux sadly :/
