### ISSUE TITLE
Issue with the last release

### ISSUE THREAD

**Issue by Sphaxtoast** [lucasassislar/nucleuscoop#39]
Hey, i wanted to test the lastest version of your project Nucleus coop, the "release 2.0 Alpha 6". When i want to start the game with 2 players an error message pop up which says it's impossible to start the program because of some "app" (don't know what it is) missing : 
- MSVCP140.dll 
![image](https://cloud.githubusercontent.com/assets/22945094/19539885/3519a4fa-965c-11e6-9027-23e1fcde5115.png)
- VCRUNTIME140.dll 
![image](https://cloud.githubusercontent.com/assets/22945094/19539910/562f26ec-965c-11e6-92dd-993be1180888.png)
- again the same file missing VCRUNTIME140.dll 
![image](https://cloud.githubusercontent.com/assets/22945094/19539910/562f26ec-965c-11e6-92dd-993be1180888.png)
- and then again MSVCP140.dll 
![image](https://cloud.githubusercontent.com/assets/22945094/19539942/7cc5f182-965c-11e6-8753-4602ab0447ad.png)

All these error messages end with saying that "i should try to reinstall these "app" to fix this problem"
(sorry for all the error message box in french but i tried to sum it up the best i can)

Thanks for your future reply and i hope you will help me to cross this hurdle! Thanks again.

**Comment by vharris** [comment]
I had the same issue. Grab and install both of those files if you have an 64-bit Windows.

**Comment by Sphaxtoast** [comment]
Hey thanks for replying! Can you tell me how/where do i get these files ? Thanks again!

**Comment by vharris** [comment]
Sorry about that:

https://www.microsoft.com/en-us/download/details.aspx?id=48145
