### ISSUE TITLE
How to make xbox1 controller default to bottom screen in Borderlands 2 (2-Player)

### ISSUE THREAD

**Issue by EScann15** [lucasassislar/nucleuscoop#4]
Title says the problem. When playing with 2 players, using kb+m and 1 xbone controller, the xbox one controller always defaults to the top screen when i would rather the top be keyboard and mouse (me) and the bottom be xbone controller (my girlfriend). 

I have tried switching saves and making player 1 on the bottom in the split screen options(in the split play application), every combination of switching who is top and bottom and selecting the keyboard player option.

I just don't know what to do so right now I am just playing on the bottom, which isn't even that big of a deal just a slight annoyance.

Any help at all would be appreciated.

And THANK YOU SO MUCH for this my girlfriend and I use it every day!

**Comment by calvinblanes** [comment]
Hi, I got the same problem but I figured out a solution, if I remember right the trick was in the order that u add the players, try doing it backwards and that should solve the problem!

**Comment by mirhl** [comment]
You can force any player order you want in XInput games with [x360ce](http://pcgamingwiki.com/wiki/Xbox_360_Controller_Emulator#Unset_controller_from_first_player).

**Comment by lucasassislar** [comment]
What calvinblanes told is the way to go, just reverse put the players.
