### ISSUE TITLE
BL1 - Save game player 2 not working

### ISSUE THREAD

**Issue by BartDirven** [lucasassislar/nucleuscoop#46]
Hi there,

I've managed to get BL1 working with two Xbox360 controllers plugged in and so far everything has been working fine. However, when we wanted to play again today (for the second time), both instances of the game loaded the save file from player 1. I've restarted the program several times, but to no avail.
Where can I check whether the save game for player 2 even exists and/or how can I make sure that it writes to two different save files in the future?

Thanks!

**Comment by Sphaxtoast** [comment]
To look at your saves, you need to go to /MyDocuments/MyGames/Borderlands2/WillowGame/SaveData/76561198503567285 (it can be any other random number).
In this file you'll see "profilbin + Save0001.sav + Save0001.sav.bak" these elements represent your save.

Now if you want the game to consider your saves you need to put these elements in the number file (for example: 76561198503567285 ).
If apparently you played the game with two players you should have in this file number "profilbin(2) + Save0002.sav + Save0002.sav.bak" (or other number it depends how the game or you renamed it). These elements represent the second save of the game and if there is noting this file you have to search these elements and put them in the document: /MyDocuments/MyGames/Borderlands2/WillowGame/SaveData/76561198503567285 (or any other random number)

I hope i helped you, sorry for bad english!

**Comment by BartDirven** [comment]
Thanks for the reply!

Unfortunately, no save game for player 2 existed, but I managed to get it working by making a save game for both players by just creating two characters on the player 1 screen (which creates a Save0001.sav and Save0002.sav), then restart the game and then both play with one of these characters. My save folder now has Save0001.sav, Save0002.sav and profile.bin. So far, it works!
