### ISSUE TITLE
Stop to put binaries in source control

### ISSUE THREAD

**Issue by mirh** [lucasassislar/nucleuscoop#66]
There is release section for that.

**Comment by lucasassislar** [comment]
This is something I done to save on time (I added a Post-Build script that zips the release folder and updates the PreAlpha file directly; so every time I push a commit there's already a live pre-alpha version).
I need to configure an automated server to do that, but last time I spent too much time doing that (so I just ignored and moved forwad with the zips directly on github).
Its somethig I want to remove too but right now its the easiest way to test. (I still upload releases on the release section tho, just needs further testing to get it there).

**Comment by mirh** [comment]
I mean, I see it's handy for you and all. And after all you are even the only developer (even because you are late on merging PR C:)
Though, it's a big burden when-ever one wants to clone the repo.

**Comment by mirh** [comment]
Good. 
Now, I guess like you could tinker/filter a bit with git history to clean it, but whatever.
