### ISSUE TITLE
Aliens Colonial Marines FPS problem

### ISSUE THREAD

**Issue by luisloco** [lucasassislar/nucleuscoop#76]
when you play the Aliens Colonial Marines game as 2 players player 2 runs at less fps but if you make a change with the alt + tab the fps player 1 is inverted with less fps and player 2 with 60 fps then in moments they go down a lot the fps is in player 1 or player to make the change with the alt + tab only happens to the one that touches less fps instead does not happen.

![error](https://user-images.githubusercontent.com/5092869/30125860-80399558-92ff-11e7-9b6d-5a76623d2261.png)

**Comment by lucasassislar** [comment]
Strange, Aliens Colonial Marines is one of the games that I tested the least.
I'm assigning this as bug that needs fixing in the Colonial Marines code, will have to take a look.

**Comment by luisloco** [comment]
@lucasassislar test with 3 players works almost perfect if slowness as in 2 players it seems that the game tubiera running less than 15 fps is unplayable I will try to make a video so that you can see the problems.

**Comment by r-mach** [comment]
I close this as this is related to #64
